### ISSUE TITLE
Lock error

### ISSUE THREAD

**Issue by jpvincent** [iteratec/OpenSpeedMonitor#33]
Hi
I'm using OSM together with mysql, grafana and webpagetest but after several docker-compose up/down, the OSM service throws a java lock error.

here is the output of `docker-compose --file osm-wpt-grafana.docker-compose.yml up`

```
osm_service           | 2018/01/09 17:21:32 Waiting for host: osm_mysql:3306
osm_service           | 2018/01/09 17:21:32 Problem with dial: dial tcp 172.18.0.2:3306: getsockopt: connection refused. Sleeping 5s
osm_mysql             | 2018-01-09T17:21:33.096992Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
osm_mysql             | 2018-01-09T17:21:33.105103Z 0 [Note] mysqld (mysqld 5.7.20) starting as process 1 ...
osm_mysql             | 2018-01-09T17:21:33.109802Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
osm_mysql             | 2018-01-09T17:21:33.116234Z 0 [Note] InnoDB: PUNCH HOLE support available
osm_mysql             | 2018-01-09T17:21:33.116279Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
osm_mysql             | 2018-01-09T17:21:33.116282Z 0 [Note] InnoDB: Uses event mutexes
osm_mysql             | 2018-01-09T17:21:33.116284Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
osm_mysql             | 2018-01-09T17:21:33.116286Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
osm_mysql             | 2018-01-09T17:21:33.116288Z 0 [Note] InnoDB: Using Linux native AIO
osm_mysql             | 2018-01-09T17:21:33.118080Z 0 [Note] InnoDB: Number of pools: 1
osm_mysql             | 2018-01-09T17:21:33.120846Z 0 [Note] InnoDB: Using CPU crc32 instructions
osm_mysql             | 2018-01-09T17:21:33.124384Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
osm_mysql             | 2018-01-09T17:21:33.141765Z 0 [Note] InnoDB: Completed initialization of buffer pool
osm_mysql             | 2018-01-09T17:21:33.150582Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
osm_mysql             | 2018-01-09T17:21:33.184645Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
osm_mysql             | 2018-01-09T17:21:33.202689Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 25913390
osm_mysql             | 2018-01-09T17:21:33.202732Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 25913399
osm_mysql             | 2018-01-09T17:21:33.202737Z 0 [Note] InnoDB: Database was not shutdown normally!
osm_mysql             | 2018-01-09T17:21:33.202740Z 0 [Note] InnoDB: Starting crash recovery.
osm_mysql             | 2018-01-09T17:21:33.732962Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
osm_mysql             | 2018-01-09T17:21:33.733004Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
osm_mysql             | 2018-01-09T17:21:33.733939Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
osm_mysql             | 2018-01-09T17:21:33.802036Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
osm_mysql             | 2018-01-09T17:21:33.806937Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
osm_mysql             | 2018-01-09T17:21:33.806965Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
osm_mysql             | 2018-01-09T17:21:33.807925Z 0 [Note] InnoDB: 5.7.20 started; log sequence number 25913399
osm_mysql             | 2018-01-09T17:21:33.808460Z 0 [Note] Plugin 'FEDERATED' is disabled.
osm_mysql             | 2018-01-09T17:21:33.809185Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
osm_mysql             | 2018-01-09T17:21:33.860405Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
osm_mysql             | 2018-01-09T17:21:33.868354Z 0 [Warning] CA certificate ca.pem is self signed.
osm_mysql             | 2018-01-09T17:21:33.874567Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
osm_mysql             | 2018-01-09T17:21:33.874658Z 0 [Note] IPv6 is available.
osm_mysql             | 2018-01-09T17:21:33.874679Z 0 [Note]   - '::' resolves to '::';
osm_mysql             | 2018-01-09T17:21:33.874723Z 0 [Note] Server socket created on IP: '::'.
osm_mysql             | 2018-01-09T17:21:33.920132Z 0 [Note] InnoDB: Buffer pool(s) load completed at 180109 17:21:33
osm_mysql             | 2018-01-09T17:21:33.926972Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.927061Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.928007Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.928036Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.928916Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.982726Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:33.982820Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
osm_mysql             | 2018-01-09T17:21:34.219255Z 0 [Note] Event Scheduler: Loaded 0 events
osm_mysql             | 2018-01-09T17:21:34.219661Z 0 [Note] mysqld: ready for connections.
osm_mysql             | Version: '5.7.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
osm_mysql             | 2018-01-09T17:21:34.219709Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
osm_mysql             | 2018-01-09T17:21:34.219723Z 0 [Note] Beginning of list of non-natively partitioned tables
osm_mysql             | 2018-01-09T17:21:34.971944Z 0 [Note] End of list of non-natively partitioned tables
osm_service           | 2018/01/09 17:21:37 Connected to tcp://osm_mysql:3306
osm_service           | complete osm config file gets prepared
osm_service           | log4j:WARN No appenders could be found for logger (org.apache.tomcat.util.modeler.Registry).
osm_service           | log4j:WARN Please initialize the log4j system properly.
osm_service           | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
osm_service           | start reading external config-file
osm_service           | Config file classpath:OpenSpeedMonitor-config.yml not found
osm_service           | resource exists: /home/osm/.grails/OpenSpeedMonitor-config.yml
osm_service           | 
osm_service           | Configuring Spring Security Core ...
osm_service           | ... finished configuring Spring Security Core
osm_service           | 
osm_service           | 
osm_service           | Configuring Spring Security UI ...
osm_service           | ... finished configuring Spring Security UI
osm_service           | 
```

Here there is a long wait, then the java error and a proper exit 0 :

```
osm_service           | Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
osm_service           | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
osm_service           | 	at java.lang.Thread.run(Thread.java:745)
osm_service           | Caused by: java.lang.reflect.InvocationTargetException
osm_service           | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
osm_service           | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
osm_service           | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
osm_service           | 	at java.lang.reflect.Method.invoke(Method.java:498)
osm_service           | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
osm_service           | 	... 1 more
osm_service           | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springLiquibase_dataSource': Invocation of init method failed; nested exception is liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by a07425138e9d (172.18.0.3) since 1/8/18 11:52 AM
osm_service           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
osm_service           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
osm_service           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
osm_service           | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
osm_service           | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
osm_service           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
osm_service           | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
osm_service           | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
osm_service           | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
osm_service           | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
osm_service           | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
osm_service           | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
osm_service           | 	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
osm_service           | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
osm_service           | 	at grails.boot.GrailsApp.run(GrailsApp.groovy:55)
osm_service           | 	at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
osm_service           | 	at grails.boot.GrailsApp.run(GrailsApp.groovy:363)
osm_service           | 	at grails.boot.GrailsApp$run.call(Unknown Source)
osm_service           | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
osm_service           | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
osm_service           | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
osm_service           | 	at openspeedmonitor.Application.main(Application.groovy:17)
osm_service           | 	... 6 more
osm_service           | Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by a07425138e9d (172.18.0.3) since 1/8/18 11:52 AM
osm_service           | 	at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:184)
osm_service           | 	at liquibase.Liquibase.update(Liquibase.java:196)
osm_service           | 	at liquibase.Liquibase.update(Liquibase.java:192)
osm_service           | 	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:434)
osm_service           | 	at org.grails.plugins.databasemigration.liquibase.GrailsLiquibase.performUpdate(GrailsLiquibase.groovy:80)
osm_service           | 	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:391)
osm_service           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
osm_service           | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
osm_service           | 	... 27 more
osm_service           | 2018/01/09 17:27:33 Command finished successfully.
osm_service exited with code 0
```

Here is my `docker-compose.yml` file : 

```yml
version: '3'

services:

  osm:
    image: iteratec/openspeedmonitor:4.4.0
    container_name: osm_service
    entrypoint: dockerize -wait tcp://osm_mysql:3306 -timeout 60s /entrypoint.sh
    ports:
     - "8080:8080"
    environment:
      MYSQL_HOST: osm_mysql
      MYSQL_DATABASE: osm
      MYSQL_USER: osm
      MYSQL_PASSWORD: osm
      OSM_ADMIN_USER: admin
      OSM_ADMIN_PASSWORD: admin
      OSM_ROOT_USER: root
      OSM_ROOT_PASSWORD: root
      ENABLE_DETAIL_ANALYSIS: 'false'
      OSM_URL: 'http://localhost:8080'
      DETAIL_ANALYSIS_URL: 'http://localhost:8088'
      API_KEY_DETAIL_ANALYSIS: 'api_key_detail_analysis'

  osm_mysql:
    image: mysql:5.7.20
    container_name: osm_mysql
    volumes:
      - ./data/osm_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_passwd
      MYSQL_DATABASE: osm
      MYSQL_USER: osm
      MYSQL_PASSWORD: osm
    ports:
      - "3306:3306"

  ssio_grafana:
    image: grafana/grafana:4.6.2
    container_name: ssio_grafana
    depends_on:
      - graphite
    links:
      - graphite
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=hdeAga76VG6ga7plZ1
      - GF_SECURITY_ADMIN_USER=sitespeedio
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: always

  graphite:
    image: sitespeedio/graphite:1.0.2-2-b
    container_name: graphite
    ports:
      - "2003:2003"
      - "8070:80"
    restart: always
    volumes:
      - ./data/graphite/whisper:/opt/graphite/storage/whisper
      # In production you should configure/map these to your container
      # Download from https://github.com/sitespeedio/sitespeed.io/tree/master/docker/graphite
      #- ./graphite/graphite.db:/opt/graphite/storage/graphite.db
      - ./conf-graphes/graphite/conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      #- ./graphite/conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
      #- ./graphite/conf/carbon.conf:/opt/graphite/conf/carbon.conf

  ssio_grafana-setup:
    image: sitespeedio/grafana-bootstrap:sitespeed.io-4.6
    container_name: ssio_setup
    links:
      - ssio_grafana
    environment:
      - GF_PASSWORD=hdeAga76VG6ga7plZ1
      - GF_USER=sitespeedio
      - GF_API=http://ssio_grafana:3000/api
    volumes:
      - ./conf-graphes/dashboards:/dashboards


volumes:
  grafana:
  whisper:
  osm_mysql_data:
    driver: local
  osmda_mongodb_data:
    driver: local
  wpt_logs:
    driver: local
  wpt_results:
    driver: local
```

Note that I disabled the detail-analysis micro-service.
I tried 
- to remove all machines but mysql and osm, 
- to lock the mysql version
- docker down, restart the docker machine (I'm on MacOS), docker up

It worked like a charm for a month, with and up/down.
My guess is that the last time I aborted the `docker-compose up` was in the middle of osm_service trying to launch, then a lockfile happened and I dont see how to remove it.

Can you help ?
